### ISSUE TITLE
멀티 모듈 도입 여부 결정

### ISSUE THREAD

**Issue by soulplay95** [boostcampwm-2022/android11-almost-there#2]
Q. 멀티 모듈을 도입할 것인가?
Q. 도입한다면 처음에 / 나중에 도입할 것인가?

**Comment by tnwlsgk1002** [comment]
**멀티 모듈을 도입하자는 의견**

- 한 가지 모듈에서 작업을 하다 보면, 팀 내에서 결정한 규칙이나 다른 레이어의 클래스를 사용할 수 있는데, 모듈을 분리하여 강제로 다른 레이어의 클래스를 사용하지 못하도록 한다면 실수를 방지하는데 도움이 될 것이다.
- 이번에 못쓰면 취업 전까지 절대 멀티모듈을 못쓸것이다. 학습 목적으로 한 번 시도해보는 것이 좋을 것 같다.

**Comment by tnwlsgk1002** [comment]
멀티 모듈을 도입하지 말자 or 나중에 하자는 의견

**Comment by tnwlsgk1002** [comment]
멘토님 의견

**Comment by tnwlsgk1002** [comment]
멀티 모듈 MeetUp
- [호현's 발표 자료](https://www.canva.com/design/DAFR76hOKds/WxPMQsqKGd5Vd1ZK7rVANA/view#1
)
- [멀티 모듈 TALK](https://www.figma.com/file/nKCAyfZ03VVKF8M5suEBFx/%EB%A9%80%ED%8B%B0-%EB%AA%A8%EB%93%88-Talk?node-id=0%3A1&t=sX1W3sQlj6eYGbnZ-0)

**Comment by tnwlsgk1002** [comment]
결론
- 팀 그라운드 룰에 따라 다수결로 결정
=> 처음에 도입하는 것으로 결정!
