### ISSUE TITLE
약속 상세화면

### ISSUE THREAD

**Issue by swjw13** [boostcampwm-2022/android11-almost-there#27]

**Comment by tnwlsgk1002** [comment]
# 설계
## 화면 로직
- Activity로 이동 시 인자값으로 약속 코드를 받는다.
- 약속 코드를 Repository에 보내서 약속 정보를 받아온다.
- 받아온 약속 정보를 출력한다.

**Comment by tnwlsgk1002** [comment]
# 기존 구현 사항

# 개선 사항
